import Layout from "@/components/templates/Layout";
import TanstackQueryProvider from "../partials/providers/TanstackQueryProvider";
import { ShowModalContext } from "@/partials/context/ShowModalContext";
import AuthForm from "@/components/templates/AuthForm";
import ModalContainer from "@/partials/containers/ModalContainer";
import { Toaster } from "react-hot-toast";

import "../styles/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <div>
          <TanstackQueryProvider>
            <ShowModalContext>
              <Layout>
                {children}
                <AuthForm />
                <ModalContainer />
              </Layout>
            </ShowModalContext>
          </TanstackQueryProvider>
          <Toaster />
        </div>
      </body>
    </html>
  );
}

export default RootLayout;
