import Layout from "@/components/templates/Layout";
import "../styles/globals.css";
import TanstackQueryProvider from "../partials/providers/TanstackQueryProvider";
import { ShowModalContext } from "@/partials/context/ShowModalContext";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <div className="container">
          <TanstackQueryProvider>
            <ShowModalContext>
              <Layout>{children}</Layout>
            </ShowModalContext>
          </TanstackQueryProvider>
          <Toaster />
        </div>
      </body>
    </html>
  );
}

export default RootLayout;
